# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ajoutcont.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from ListeContrat import *
from Controle import *
from enreclient import Ui_Dialog as enrecli


class Ui_Dialog(object):
        def __init__(self,Agence):
                self.Agence=Agence

        def showDialog(self,str,bool):
                msgBox = QMessageBox()
                if bool==False:
                        msgBox.setIcon(QMessageBox.Warning)
                else:
                        msgBox.setIcon(QMessageBox.Information)
                msgBox.setText(str)
                msgBox.setWindowTitle("Advertissement")
                msgBox.setStandardButtons(QMessageBox.Ok)
                msgBox.exec()

        
        def ajoutcon(self):
                cin =self.lineEdit.text()
                if c_cin(cin)==False:
                        self.showDialog("CIN Invalide !",False)
                        self.lineEdit.setText("")
                        return
                if cin_existe(cin,self.Agence.ListeClient.liste)==False:
                        msg = QMessageBox()
                        msg.setIcon(QMessageBox.Information)
                        msg.setText("C'est un Nouveau Client, Voulez-vous l'enregistrer")
                        msg.setWindowTitle("Attention")
                        msg.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
                        if msg.exec_() == QMessageBox.Yes:
                                self.windowajouterclient=QDialog()
                                self.ui=enrecli(self.Agence)
                                self.ui.setupUi(self.windowajouterclient)
                                self.windowajouterclient.show()
                                return
                        else:
                                self.lineEdit.setText(""); self.lineEdit_2.setText(""); self.lineEdit_3.setText("")
                                self.lineEdit_4.setText(""); self.lineEdit_5.setText("")
                                return
                
                p1matr=self.lineEdit_2.text()
                p2matr=self.lineEdit_3.text()
                matr=p1matr+" TUN "+p2matr
                if c_matricule(matr)==False:
                        self.showDialog("Matricule Invalide !",False)
                        self.lineEdit_2.setText("")
                        self.lineEdit_3.setText("")
                        return
                if mat_existe(matr,self.Agence.Parc.parc)==False: 
                        self.showDialog("Matricule n'existe !",False)
                        self.lineEdit_2.setText("")
                        self.lineEdit_3.setText("")
                        return
                if c_louee(matr,self.Agence.Parc):
                        self.showDialog("La Voiture est Louée !",False)
                        self.lineEdit_2.setText("")
                        self.lineEdit_3.setText("")
                        return
                        
                
                datec=self.lineEdit_4.text()
                if c_date(datec)==False:
                        self.showDialog("Date Invalide !",False)
                        self.lineEdit_4.setText("")
                        return
                
                dure=self.lineEdit_5.text()
                if c_duree(dure)==False:
                        self.showDialog("Durée Invalide !",False)
                        self.lineEdit_5.setText("")
                        return
                
                self.Agence.ListeContrat.ajout_contrat(cin,matr,datec,dure)
                self.showDialog("Contrat Signé !",True)
                self.lineEdit.setText(""); self.lineEdit_2.setText(""); self.lineEdit_3.setText("")
                self.lineEdit_4.setText(""); self.lineEdit_5.setText("")
                return


        def setupUi(self, Dialog):

                Dialog.setObjectName("Dialog")
                Dialog.resize(1393, 832)
                Dialog.setStyleSheet("background-color:LightGrey")
                self.label_7 = QtWidgets.QLabel(Dialog)
                self.label_7.setGeometry(QtCore.QRect(850, 620, 91, 71))
                self.label_7.setStyleSheet("")
                self.label_7.setText("")
                self.label_7.setPixmap(QtGui.QPixmap(":/pics/68385356-contract-rubber-stamp-grunge-design-with-dust-scratches-effects-can-be-easily-removed-for-a-clean-cr.webp"))
                self.label_7.setScaledContents(True)
                self.label_7.setObjectName("label_7")
                self.label = QtWidgets.QLabel(Dialog)
                self.label.setGeometry(QtCore.QRect(-10, -5, 1421, 841))
                self.label.setText("")
                self.label.setPixmap(QtGui.QPixmap(":/pics/b3.jpg"))
                self.label.setScaledContents(True)
                self.label.setObjectName("label")
                self.label_2 = QtWidgets.QLabel(Dialog)
                self.label_2.setGeometry(QtCore.QRect(550, 30, 321, 71))
                font = QtGui.QFont()
                font.setFamily("Bernard MT Condensed")
                font.setPointSize(24)
                self.label_2.setFont(font)
                self.label_2.setStyleSheet("Background-color:none;\n"
        "color:white")
                self.label_2.setObjectName("label_2")
                self.lineEdit = QtWidgets.QLineEdit(Dialog)
                self.lineEdit.setGeometry(QtCore.QRect(562, 161, 281, 31))
                font = QtGui.QFont()
                font.setFamily("Modern No. 20")
                font.setPointSize(14)
                self.lineEdit.setFont(font)
                self.lineEdit.setStyleSheet("QLineEdit{\n"
        "border-style: outset;\n"
        "background-color:white;\n"
        "    border-radius: 10px;\n"
        "}\n"
        "QLineEdit:focus{\n"
        "border:1.5px solid\n"
        "}\n"
        "")
                self.lineEdit.setObjectName("lineEdit")
                self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
                self.lineEdit_2.setGeometry(QtCore.QRect(560, 250, 91, 31))
                font = QtGui.QFont()
                font.setFamily("Modern No. 20")
                font.setPointSize(14)
                self.lineEdit_2.setFont(font)
                self.lineEdit_2.setStyleSheet("QLineEdit{\n"
        "border-style: outset;\n"
        "background-color:white;\n"
        "    border-radius: 10px;\n"
        "}\n"
        "QLineEdit:focus{\n"
        "border:1.5px solid\n"
        "}\n"
        "")
                self.lineEdit_2.setObjectName("lineEdit_2")
                self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
                self.lineEdit_3.setGeometry(QtCore.QRect(720, 250, 121, 31))
                font = QtGui.QFont()
                font.setFamily("Modern No. 20")
                font.setPointSize(14)
                self.lineEdit_3.setFont(font)
                self.lineEdit_3.setStyleSheet("QLineEdit{\n"
        "border-style: outset;\n"
        "background-color:white;\n"
        "    border-radius: 10px;\n"
        "}\n"
        "QLineEdit:focus{\n"
        "border:1.5px solid\n"
        "}\n"
        "")
                self.lineEdit_3.setObjectName("lineEdit_3")
                self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
                self.lineEdit_4.setGeometry(QtCore.QRect(560, 340, 281, 31))
                font = QtGui.QFont()
                font.setFamily("Modern No. 20")
                font.setPointSize(14)
                self.lineEdit_4.setFont(font)
                self.lineEdit_4.setStyleSheet("QLineEdit{\n"
        "border-style: outset;\n"
        "background-color:white;\n"
        "    border-radius: 10px;\n"
        "}\n"
        "QLineEdit:focus{\n"
        "border:1.5px solid\n"
        "}\n"
        "")
                self.lineEdit_4.setObjectName("lineEdit_4")
                self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
                self.lineEdit_5.setGeometry(QtCore.QRect(562, 440, 281, 31))
                font = QtGui.QFont()
                font.setFamily("Modern No. 20")
                font.setPointSize(14)
                self.lineEdit_5.setFont(font)
                self.lineEdit_5.setStyleSheet("QLineEdit{\n"
        "border-style: outset;\n"
        "background-color:white;\n"
        "    border-radius: 10px;\n"
        "}\n"
        "QLineEdit:focus{\n"
        "border:1.5px solid\n"
        "}\n"
        "")
                self.lineEdit_5.setObjectName("lineEdit_5")
                self.pushButton = QtWidgets.QPushButton(Dialog)
                self.pushButton.setGeometry(QtCore.QRect(570, 630, 261, 51))
                font = QtGui.QFont()
                font.setPointSize(20)
                font.setBold(True)
                font.setWeight(75)
                self.pushButton.setFont(font)
                self.pushButton.setStyleSheet("QPushButton{\n"
        "border-style: outset;\n"
        "background-color:DarkCyan;\n"
        "    border-radius: 10px;\n"
        "}\n"
        "QPushButton:hover{\n"
        "background-color:MediumSeaGreen\n"
        "}")
                self.pushButton.setObjectName("pushButton")
                self.label_3 = QtWidgets.QLabel(Dialog)
                self.label_3.setGeometry(QtCore.QRect(660, 250, 51, 31))
                font = QtGui.QFont()
                font.setFamily("Segoe UI Variable Small Semibol")
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.label_3.setFont(font)
                self.label_3.setStyleSheet("background-color:none;\n"
        "color:white")
                self.label_3.setObjectName("label_3")

                self.retranslateUi(Dialog)
                QtCore.QMetaObject.connectSlotsByName(Dialog)
                self.pushButton.clicked.connect(self.ajoutcon)

        def retranslateUi(self, Dialog):
                _translate = QtCore.QCoreApplication.translate
                Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
                self.label_2.setText(_translate("Dialog", "Contrat De Location"))
                self.lineEdit.setPlaceholderText(_translate("Dialog", "C.I.N"))
                self.lineEdit_2.setPlaceholderText(_translate("Dialog", "000"))
                self.lineEdit_3.setPlaceholderText(_translate("Dialog", "0000"))
                self.lineEdit_4.setPlaceholderText(_translate("Dialog", "Date du Contrat"))
                self.lineEdit_5.setPlaceholderText(_translate("Dialog", "Durée de Location"))
                self.pushButton.setText(_translate("Dialog", "Save"))
                self.label_3.setText(_translate("Dialog", "TUN"))
import mothak6


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
