# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modifcont.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from Controle import *


class Ui_Dialog(object):
    def __init__(self,Agence):
        self.Agence=Agence

    def showDialog(self,str,bool):
        msgBox = QMessageBox()
        if bool==False:
            msgBox.setIcon(QMessageBox.Warning)
        else:
            msgBox.setIcon(QMessageBox.Information)
        msgBox.setText(str)
        msgBox.setWindowTitle("Advertissement")
        msgBox.setStandardButtons(QMessageBox.Ok)
        msgBox.exec()

    def radio1(self):
        self.lineEdit.setReadOnly(False)
        self.lineEdit_2.setReadOnly(False)

        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_3.setText("")   
        self.lineEdit_4.setText("") 


    def radio2(self):
        self.lineEdit_3.setReadOnly(False)
        self.lineEdit_4.setReadOnly(False)

        self.lineEdit.setReadOnly(True)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit.setText("")   
        self.lineEdit_2.setText("") 


    def modifier(self):
        if self.radioButton.isChecked():
                num=self.lineEdit.text()
                dat=self.lineEdit_2.text()

                if c_numcont(num)==False:
                    self.showDialog("Numéro Invalide !",False)
                    self.lineEdit.setText("")
                    self.lineEdit_2.setText("")
                    return
                if  contrat_existe(num,self.Agence.ListeContrat.listecont)==False:
                    self.showDialog("Contrat N'existe pas !",False)
                    self.lineEdit.setText("")
                    self.lineEdit_2.setText("")
                    return
                if c_date(dat)==False:
                    self.showDialog("Date Invalide !",False)
                    self.lineEdit.setText("")
                    self.lineEdit_2.setText("")
                    return

                self.Agence.ListeContrat.modifier_date(num,dat)
                self.showDialog("Modification Terminé !",True)
                self.lineEdit.setText("")
                self.lineEdit_2.setText("")
                return

        if self.radioButton_2.isChecked():
                num=self.lineEdit_3.text()
                dure=self.lineEdit_4.text()
                if c_numcont(num)==False:
                    self.showDialog("Numéro Invalide !",False)
                    self.lineEdit_3.setText("")
                    self.lineEdit_4.setText("")
                    return
                if  contrat_existe(num,self.Agence.ListeContrat.listecont)==False:
                    self.showDialog("Contrat N'existe pas !",False)
                    self.lineEdit_3.setText("")
                    self.lineEdit_4.setText("")
                    return
                if c_duree(dure)==False:
                    self.showDialog("Prolongation Invalide !",False)
                    self.lineEdit_3.setText("")
                    self.lineEdit_4.setText("")
                    return

                self.Agence.ListeContrat.modifier_duree(num,dure)
                self.Agence.ListeContrat.modifier_payer(num)
                self.showDialog("Modification Terminé !",True)
                self.lineEdit_3.setText("")
                self.lineEdit_4.setText("")
 

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1394, 836)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(-180, -15, 1701, 871))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/pics/b3.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(540, 30, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white")
        self.label_2.setObjectName("label_2")
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setGeometry(QtCore.QRect(110, 280, 321, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("color:white")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(110, 450, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("color:white")
        self.radioButton_2.setObjectName("radioButton_2")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(540, 300, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"border-style: outset;\n"
"background-color:white;\n"
"    border-radius: 10px;\n"
"}\n"
"QLineEdit:focus{\n"
"border:1.5px solid\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(882, 300, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"border-style: outset;\n"
"background-color:white;\n"
"    border-radius: 10px;\n"
"}\n"
"QLineEdit:focus{\n"
"border:1.5px solid\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(540, 460, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(14)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"border-style: outset;\n"
"background-color:white;\n"
"    border-radius: 10px;\n"
"}\n"
"QLineEdit:focus{\n"
"border:1.5px solid\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(882, 460, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(14)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("QLineEdit{\n"
"border-style: outset;\n"
"background-color:white;\n"
"    border-radius: 10px;\n"
"}\n"
"QLineEdit:focus{\n"
"border:1.5px solid\n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(550, 640, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"border-style: outset;\n"
"background-color:DarkCyan;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:MediumSeaGreen\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.pushButton.clicked.connect(self.modifier)
        self.radioButton.toggled.connect(self.radio1)
        self.radioButton_2.toggled.connect(self.radio2)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Modification"))
        self.radioButton.setText(_translate("Dialog", "Date de Location"))
        self.radioButton_2.setText(_translate("Dialog", "Durée De Location"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", " N ° Contrat"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", " Nouvelle Date"))
        self.lineEdit_3.setPlaceholderText(_translate("Dialog", " N ° Contrat"))
        self.lineEdit_4.setPlaceholderText(_translate("Dialog", " Prolongation"))
        self.pushButton.setText(_translate("Dialog", "Modify"))
import mothak6


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
