# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modifclient.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from Controle import *


class Ui_Dialog(object):
    def __init__(self,Agence):
        self.Agence=Agence

    def showDialog(self,str,bool):
        msgBox = QMessageBox()
        if bool==False:
            msgBox.setIcon(QMessageBox.Warning)
        else:
            msgBox.setIcon(QMessageBox.Information)
        msgBox.setText(str)
        msgBox.setWindowTitle("Advertissement")
        msgBox.setStandardButtons(QMessageBox.Ok)
        msgBox.exec()

    def radio1(self):
        self.lineEdit.setReadOnly(False)
        self.lineEdit_4.setReadOnly(False)

        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setText("")
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setText("")
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setText("")
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setText("")
    
    def radio2(self):
        self.lineEdit_2.setReadOnly(False)
        self.lineEdit_5.setReadOnly(False)

        self.lineEdit.setReadOnly(True)
        self.lineEdit.setText("")
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setText("")
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setText("")
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setText("")
    
    def radio3(self):
        self.lineEdit_3.setReadOnly(False)
        self.lineEdit_6.setReadOnly(False)

        self.lineEdit.setReadOnly(True)
        self.lineEdit.setText("")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setText("")
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setText("")
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setText("")
    
    def modifier(self):
        if self.radioButton.isChecked():
            cin=self.lineEdit.text()
            if c_cin(cin)==False:
                self.showDialog("CIN Invalide !",False)
                self.lineEdit.setText("")
                self.lineEdit_4.setText("")
                return
            if cin_existe(cin,self.Agence.ListeClient.liste)==False:
                self.showDialog("CIN N'existe Pas !",True)
                self.lineEdit.setText("")
                self.lineEdit_4.setText("")
                return

            adresse=self.lineEdit_4.text()
            if len(adresse)<4:
                self.showDialog("Email Invalide !",False)
                self.lineEdit.setText("")
                self.lineEdit_4.setText("")
                return

            self.Agence.ListeClient.modif_adresse_client(cin,adresse)
            self.showDialog("Modification Terminée !",True)
            self.lineEdit.setText("")
            self.lineEdit_4.setText("")
            return

        if self.radioButton_2.isChecked():
            cin=self.lineEdit_2.text()
            if c_cin(cin)==False:
                self.showDialog("CIN Invalide !",False)
                self.lineEdit_2.setText("")
                self.lineEdit_5.setText("")
                return
            if cin_existe(cin,self.Agence.ListeClient.liste)==False:
                self.showDialog("CIN N'existe Pas !",True)
                self.lineEdit_2.setText("")
                self.lineEdit_5.setText("")
                return
            tlf=self.lineEdit_5.text()
            if c_tlf(tlf)==False:
                self.showDialog("Numéro Invalide !",False)
                self.lineEdit_2.setText("")
                self.lineEdit_5.setText("")
                return
            
            self.Agence.modif_tlf_client(cin,tlf)
            self.showDialog("Modification Terminée !",True)
            self.lineEdit_2.setText("")
            self.lineEdit_5.setText("")
            return

        
        if self.radioButton_3.isChecked():
            cin=self.lineEdit_3.text()
            if c_cin(cin)==False:
                self.showDialog("CIN Invalide !",False)
                self.lineEdit_3.setText("")
                self.lineEdit_6.setText("")
                return
            if cin_existe(cin,self.Agence.ListeClient.liste)==False:
                self.showDialog("CIN N'existe Pas !",True)
                self.lineEdit_3.setText("")
                self.lineEdit_6.setText("")
                return
            maile=self.lineEdit_6.text()
            if c_mail(maile)==False:
                self.showDialog("Email Invalide !",False)
                self.lineEdit_3.setText("")
                self.lineEdit_6.setText("")
                return
            
            self.Agence.modif_mail_client(cin,maile)
            self.showDialog("Modification Terminée !",True)
            self.lineEdit_3.setText("")
            self.lineEdit_6.setText("")
            return
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1392, 832)
        Dialog.setStyleSheet("background-color:DodgerBlue")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(-20, -5, 1411, 841))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/pic/b2.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(620, 70, 211, 81))
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        font.setPointSize(26)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:none;\n"
"color:white")
        self.label_2.setObjectName("label_2")
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setGeometry(QtCore.QRect(140, 280, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("background-color:none;\n"
"color:white")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(140, 350, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("background-color:none;\n"
"color:white")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_3.setGeometry(QtCore.QRect(140, 450, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setStyleSheet("background-color:none;\n"
"color:white")
        self.radioButton_3.setObjectName("radioButton_3")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(460, 280, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"border-style: outset;\n"
"background-color:white;\n"
"    border-radius: 10px;\n"
"}\n"
"QLineEdit:focus{\n"
"border:1.5px solid\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(460, 360, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"border-style: outset;\n"
"background-color:white;\n"
"    border-radius: 10px;\n"
"}\n"
"QLineEdit:focus{\n"
"border:1.5px solid\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(460, 450, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(14)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"border-style: outset;\n"
"background-color:white;\n"
"    border-radius: 10px;\n"
"}\n"
"QLineEdit:focus{\n"
"border:1.5px solid\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(860, 280, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(14)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("QLineEdit{\n"
"border-style: outset;\n"
"background-color:white;\n"
"    border-radius: 10px;\n"
"}\n"
"QLineEdit:focus{\n"
"border:1.5px solid\n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(860, 360, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(14)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("QLineEdit{\n"
"border-style: outset;\n"
"background-color:white;\n"
"    border-radius: 10px;\n"
"}\n"
"QLineEdit:focus{\n"
"border:1.5px solid\n"
"}")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(860, 450, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(14)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("QLineEdit{\n"
"border-style: outset;\n"
"background-color:white;\n"
"    border-radius: 10px;\n"
"}\n"
"QLineEdit:focus{\n"
"border:1.5px solid\n"
"}")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(580, 600, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"border-style: outset;\n"
"background-color:Aquamarine;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:Aqua\n"
"}")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.pushButton.clicked.connect(self.modifier)
        self.radioButton.toggled.connect(self.radio1)
        self.radioButton_2.toggled.connect(self.radio2)
        self.radioButton_3.toggled.connect(self.radio3)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Modification"))
        self.radioButton.setText(_translate("Dialog", "Adresse"))
        self.radioButton_2.setText(_translate("Dialog", "Téléphone"))
        self.radioButton_3.setText(_translate("Dialog", "Adresse-Mail"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "C.I.N"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "C.I.N"))
        self.lineEdit_3.setPlaceholderText(_translate("Dialog", "C.I.N"))
        self.lineEdit_4.setPlaceholderText(_translate("Dialog", "Nouvelle Adresse"))
        self.lineEdit_5.setPlaceholderText(_translate("Dialog", "Nouveau Téléphone"))
        self.lineEdit_6.setPlaceholderText(_translate("Dialog", "Nouvelle Adresse-Mail"))
        self.pushButton.setText(_translate("Dialog", "Modify"))
import affc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
