# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rechcontr.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from Controle import *
from listerechcont import Ui_Dialog as lis


class Ui_Dialog(object):
    def __init__(self,Agence):
        self.Agence=Agence
    
    
    def showDialog(self,str,bool):
        msgBox = QMessageBox()
        if bool==False:
            msgBox.setIcon(QMessageBox.Warning)
        else:
            msgBox.setIcon(QMessageBox.Information)
        msgBox.setText(str)
        msgBox.setWindowTitle("Advertissement")
        msgBox.setStandardButtons(QMessageBox.Ok)
        msgBox.exec()

    def radio1(self):
        self.lineEdit.setReadOnly(False)

        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setText("")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setText("")
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setText("")
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setText("")
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setText("")
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setText("")

    def radio2(self):
        self.lineEdit_2.setReadOnly(False)
        self.lineEdit_3.setReadOnly(False)
        
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setText("")
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setText("")
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setText("")
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setText("")
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setText("")


    def radio3(self):
        self.lineEdit_4.setReadOnly(False)

        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setText("")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setText("")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setText("")
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setText("")
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setText("")
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setText("")

    def radio4(self):
        self.lineEdit_5.setReadOnly(False)

        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setText("")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setText("")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setText("")
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setText("")
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setText("")
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setText("")


    def radio5(self):
        self.lineEdit_6.setReadOnly(False)
        self.lineEdit_7.setReadOnly(False)
        
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setText("")
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setText("")
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setText("")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setText("")
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setText("")


    def chercher(self):
        if self.radioButton_2.isChecked():
                p1matr=self.lineEdit_2.text()
                p2matr=self.lineEdit_3.text()
                matr=p1matr+" TUN "+p2matr
                if c_matricule(matr)==False:
                    self.showDialog("Matricule Invalide !",False)
                    self.lineEdit_2.setText("")
                    self.lineEdit_3.setText("")
                    return
                    
                l=self.Agence.ListeContrat.recherche_contrat_matr(matr)
                self.windowlis=QDialog()
                self.ui=lis(self.Agence,l)
                self.ui.setupUi(self.windowlis)
                self.windowlis.show()
                return
                


        if self.radioButton.isChecked():
            cin=self.lineEdit.text()
            if c_cin(cin)==False:
                    self.showDialog("CIN Invalide !",False)
                    self.lineEdit.setText("")
                    return

            l=self.Agence.ListeContrat.recherche_contrat_cin(cin)
            
            self.windowlis=QDialog()
            self.ui=lis(self.Agence,l)
            self.ui.setupUi(self.windowlis)
            self.windowlis.show()
            
            return

        if self.radioButton_3.isChecked():
            dat=self.lineEdit_4.text()
            if c_date(dat)==False:
                    self.showDialog("Date Invalide !",False)
                    self.lineEdit_4.setText("")
                    return
            l=self.Agence.ListeContrat.recherche_contrat_datee(dat)
            
            self.windowlis=QDialog()
            self.ui=lis(self.Agence,l)
            self.ui.setupUi(self.windowlis)
            self.windowlis.show()
            return
            

        if self.radioButton_4.isChecked():
            dure=self.lineEdit_5.text()
            if c_duree(dure)==False:
                    self.showDialog("Durée Invalide !",False)
                    self.lineEdit_5.setText("")
                    return
            l=self.Agence.ListeContrat.recherche_contrat_duree(dure)
            
            self.windowlis=QDialog()
            self.ui=lis(self.Agence,l)
            self.ui.setupUi(self.windowlis)
            self.windowlis.show()
            return
            

        if self.radioButton_5.isChecked():
            d1=self.lineEdit_6.text()
            d2=self.lineEdit_7.text()
            if c_date(d1)==False or c_date(d2)==False or compare_date(d1,d2)==False:
                self.showDialog("Date Invalide !",False)
                self.lineEdit_6.setText("")
                self.lineEdit_7.setText("")
                return
            l=self.Agence.ListeContrat.recherche_contrat_date(d1,d2)
            
            self.windowlis=QDialog()
            self.ui=lis(self.Agence,l)
            self.ui.setupUi(self.windowlis)
            self.windowlis.show()
            return
            



    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1392, 835)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(-110, -5, 1601, 851))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/pics/b3.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(570, 40, 301, 61))
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white")
        self.label_2.setObjectName("label_2")
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setGeometry(QtCore.QRect(130, 230, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("color:white")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(130, 300, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("color:white")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_3.setGeometry(QtCore.QRect(130, 390, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setStyleSheet("color:white")
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_4.setGeometry(QtCore.QRect(130, 470, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setStyleSheet("color:white")
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_5.setGeometry(QtCore.QRect(130, 550, 531, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setStyleSheet("color:white")
        self.radioButton_5.setObjectName("radioButton_5")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(560, 700, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"border-style: outset;\n"
"background-color:DarkCyan;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:MediumSeaGreen\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(770, 231, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"border-style: outset;\n"
"background-color:white;\n"
"    border-radius: 10px;\n"
"}\n"
"QLineEdit:focus{\n"
"border:1.5px solid\n"
"}\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(770, 300, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"border-style: outset;\n"
"background-color:white;\n"
"    border-radius: 10px;\n"
"}\n"
"QLineEdit:focus{\n"
"border:1.5px solid\n"
"}\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(930, 300, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(14)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"border-style: outset;\n"
"background-color:white;\n"
"    border-radius: 10px;\n"
"}\n"
"QLineEdit:focus{\n"
"border:1.5px solid\n"
"}\n"
"")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(770, 380, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(14)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("QLineEdit{\n"
"border-style: outset;\n"
"background-color:white;\n"
"    border-radius: 10px;\n"
"}\n"
"QLineEdit:focus{\n"
"border:1.5px solid\n"
"}\n"
"")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(770, 471, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(14)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("QLineEdit{\n"
"border-style: outset;\n"
"background-color:white;\n"
"    border-radius: 10px;\n"
"}\n"
"QLineEdit:focus{\n"
"border:1.5px solid\n"
"}\n"
"")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(772, 541, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(14)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("QLineEdit{\n"
"border-style: outset;\n"
"background-color:white;\n"
"    border-radius: 10px;\n"
"}\n"
"QLineEdit:focus{\n"
"border:1.5px solid\n"
"}\n"
"")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_7.setGeometry(QtCore.QRect(930, 540, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(14)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("QLineEdit{\n"
"border-style: outset;\n"
"background-color:white;\n"
"    border-radius: 10px;\n"
"}\n"
"QLineEdit:focus{\n"
"border:1.5px solid\n"
"}\n"
"")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(880, 300, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.pushButton.clicked.connect(self.chercher)
        self.radioButton.toggled.connect(self.radio1)
        self.radioButton_2.toggled.connect(self.radio2)
        self.radioButton_3.toggled.connect(self.radio3)
        self.radioButton_4.toggled.connect(self.radio4)
        self.radioButton_5.toggled.connect(self.radio5)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Recherche"))
        self.radioButton.setText(_translate("Dialog", "Recherche C.I.N"))
        self.radioButton_2.setText(_translate("Dialog", "Recherche Matricule"))
        self.radioButton_3.setText(_translate("Dialog", "Recherche Date De Location"))
        self.radioButton_4.setText(_translate("Dialog", "Recherche Durée De Location"))
        self.radioButton_5.setText(_translate("Dialog", "Recherche Location entre 2 Dates"))
        self.pushButton.setText(_translate("Dialog", "Search"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", " C.I.N"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "000"))
        self.lineEdit_3.setPlaceholderText(_translate("Dialog", "0000"))
        self.lineEdit_4.setPlaceholderText(_translate("Dialog", "Date De Location"))
        self.lineEdit_5.setPlaceholderText(_translate("Dialog", " Durée De Location"))
        self.lineEdit_6.setPlaceholderText(_translate("Dialog", " Du "))
        self.lineEdit_7.setPlaceholderText(_translate("Dialog", "Au"))
        self.label_3.setText(_translate("Dialog", "TUN"))
import mothak6


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
