# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'suppcont.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from Controle import *

class Ui_Dialog(object):

    def __init__(self,Agence):
        self.Agence=Agence

    def showDialog(self,str,bool):
        msgBox = QMessageBox()
        if bool==False:
            msgBox.setIcon(QMessageBox.Warning)
        else:
            msgBox.setIcon(QMessageBox.Information)
        msgBox.setText(str)
        msgBox.setWindowTitle("Advertissement")
        msgBox.setStandardButtons(QMessageBox.Ok)
        msgBox.exec()

    def suppcontr(self):
        num=self.lineEdit.text()
        print(num)
        if c_numcont(num)==False:
            self.showDialog("Numéro Invalide !",False)
            self.lineEdit.setText("")
            return
        if contrat_existe(num,self.Agence.ListeContrat.listecont)==False:
            self.showDialog("Contrat N'Exite pas !",False)
            self.lineEdit.setText("")
            return
        
        self.Agence.ListeContrat.supprimer_contrat(num)
        self.showDialog("Suppression Terminée !",True)
        self.lineEdit.setText("")
        return

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1393, 831)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(-30, -5, 1441, 851))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/pics/b3.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(560, 30, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(540, 260, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"border-style: outset;\n"
"background-color:white;\n"
"    border-radius: 10px;\n"
"}\n"
"QLineEdit:focus{\n"
"border:1.5px solid\n"
"}\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(560, 480, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"border-style: outset;\n"
"background-color:DarkCyan;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:MediumSeaGreen\n"
"}")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.pushButton.clicked.connect(self.suppcontr)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Suppression"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "             N ° De Contrat"))
        self.pushButton.setText(_translate("Dialog", "Delete"))
import mothak6


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
