# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enrevoit.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from Controle import *


class Ui_Dialog(object):

    def __init__(self,Agence):
        self.Agence=Agence
    
    
    def showDialog(self,str,bool):
        msgBox = QMessageBox()
        if bool==False:
            msgBox.setIcon(QMessageBox.Warning)
        else:
            msgBox.setIcon(QMessageBox.Information)
        msgBox.setText(str)
        msgBox.setWindowTitle("Advertissement")
        msgBox.setStandardButtons(QMessageBox.Ok)
        msgBox.exec()

    def enregistrer(self):
        p1matr=self.partie1matr.text()
        p2matr=self.partie2matr.text()
        matr=p1matr+" TUN "+p2matr
        if c_matricule(matr)==False:
            self.showDialog("Matricule Invalide !",False)
            self.partie1matr.setText("")
            self.partie2matr.setText("")
            return
        if mat_existe(matr,self.Agence.Parc.parc): 
            self.showDialog("Matricule Existe deja !",False)
            self.partie1matr.setText("")
            self.partie2matr.setText("")
            return

        marq=self.marque.text()
        if c_marque(marq)==False:
            self.showDialog("Marque Invalide !",False)
            self.marque.setText("")
            return

        coul=self.couleur.text()
        if c_couleur(coul)==False:
            self.showDialog("Couleur Invalide !",False)
            self.couleur.setText("")
            return

        achat=self.dateachat.text()
        if c_date(achat)==False:
            self.showDialog("Date Invalide !",False)
            self.dateachat.setText("")
            return

        prix=self.prixlocation.text()
        if c_prix(prix)==False:
            self.showDialog("Prix Invalide !",False)
            self.prixlocation.setText("")

        self.Agence.Parc.ajout_voiture(matr,marq,coul,achat,prix)
        self.showDialog("Enregistrement avec Success !",True)
        self.partie1matr.setText("")
        self.partie2matr.setText("")
        self.marque.setText("")
        self.couleur.setText("")
        self.dateachat.setText("")
        self.prixlocation.setText("")

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1394, 836)
        font = QtGui.QFont()
        font.setUnderline(True)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color:DarkSlateGrey")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(-130, -100, 1621, 1051))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/pics/b1.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(540, 40, 371, 71))
        font = QtGui.QFont()
        font.setFamily("Bernard MT Condensed")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:none;color:white")
        self.label_2.setObjectName("label_2")
        self.partie1matr = QtWidgets.QLineEdit(Dialog)
        self.partie1matr.setGeometry(QtCore.QRect(540, 180, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(16)
        self.partie1matr.setFont(font)
        self.partie1matr.setStyleSheet("QLineEdit{\n"
"border-style: outset;\n"
"background-color:white;\n"
"    border-radius: 10px;\n"
"}\n"
"QLineEdit:focus{\n"
"border:1.5px solid\n"
"}")
        self.partie1matr.setObjectName("partie1matr")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(660, 180, 55, 31))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color:none;\n"
"color:white")
        self.label_3.setObjectName("label_3")
        self.partie2matr = QtWidgets.QLineEdit(Dialog)
        self.partie2matr.setGeometry(QtCore.QRect(720, 180, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(16)
        self.partie2matr.setFont(font)
        self.partie2matr.setStyleSheet("QLineEdit{\n"
"border-style: outset;\n"
"background-color:white;\n"
"    border-radius: 10px;\n"
"}\n"
"QLineEdit:focus{\n"
"border:1.5px solid\n"
"}")
        self.partie2matr.setObjectName("partie2matr")
        self.marque = QtWidgets.QLineEdit(Dialog)
        self.marque.setGeometry(QtCore.QRect(540, 260, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(16)
        self.marque.setFont(font)
        self.marque.setStyleSheet("QLineEdit{\n"
"border-style: outset;\n"
"background-color:white;\n"
"    border-radius: 10px;\n"
"}\n"
"QLineEdit:focus{\n"
"border:1.5px solid\n"
"}")
        self.marque.setObjectName("marque")
        self.couleur = QtWidgets.QLineEdit(Dialog)
        self.couleur.setGeometry(QtCore.QRect(540, 340, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(16)
        self.couleur.setFont(font)
        self.couleur.setStyleSheet("QLineEdit{\n"
"border-style: outset;\n"
"background-color:white;\n"
"    border-radius: 10px;\n"
"}\n"
"QLineEdit:focus{\n"
"border:1.5px solid\n"
"}")
        self.couleur.setObjectName("couleur")
        self.dateachat = QtWidgets.QLineEdit(Dialog)
        self.dateachat.setGeometry(QtCore.QRect(540, 430, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(16)
        self.dateachat.setFont(font)
        self.dateachat.setStyleSheet("QLineEdit{\n"
"border-style: outset;\n"
"background-color:white;\n"
"    border-radius: 10px;\n"
"}\n"
"QLineEdit:focus{\n"
"border:1.5px solid\n"
"}")
        self.dateachat.setObjectName("dateachat")
        self.prixlocation = QtWidgets.QLineEdit(Dialog)
        self.prixlocation.setGeometry(QtCore.QRect(540, 530, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(16)
        self.prixlocation.setFont(font)
        self.prixlocation.setStyleSheet("QLineEdit{\n"
"border-style: outset;\n"
"background-color:white;\n"
"    border-radius: 10px;\n"
"}\n"
"QLineEdit:focus{\n"
"border:1.5px solid\n"
"}")
        self.prixlocation.setObjectName("prixlocation")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(570, 650, 281, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"border-style: outset;\n"
"background-color:DarkCyan;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:MediumSeaGreen\n"
"}")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.pushButton.clicked.connect(self.enregistrer)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Enregistrement"))
        self.partie1matr.setPlaceholderText(_translate("Dialog", "000"))
        self.label_3.setText(_translate("Dialog", "TUN"))
        self.partie2matr.setPlaceholderText(_translate("Dialog", "0000"))
        self.marque.setPlaceholderText(_translate("Dialog", "Marque"))
        self.couleur.setPlaceholderText(_translate("Dialog", "Couleur"))
        self.dateachat.setPlaceholderText(_translate("Dialog", "Date d\'achat"))
        self.prixlocation.setPlaceholderText(_translate("Dialog", "Prix de location ($)"))
        self.pushButton.setText(_translate("Dialog", "Save"))
import mothak2qrc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
